name: namer_app
description: A new Flutter project.
version: 0.0.1+1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^6.1.0  # Use a version that supports null safety
  latlong2: ^0.8.2       # Update to version compatible with null safety

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
